### ISSUE TITLE
integration drone

### ISSUE THREAD

**Issue by lucasantoro** [bekirbostanci/ros_pozyx_simulation#1]
Good evening,
is it possible to use your ros package into another simulation, in which i'm usung a drone (PX4 flight stack)?
Thank you very much for your time

**Comment by bekirbostanci** [comment]
Hi luca
Which of the simulation want to use? I can help for your aim. This package use base on python and it can change easly.

**Comment by lucasantoro** [comment]
Good evening, my idea is to use this package and integrate it into gazebo simulation where i'm simulating a drone with PX4 flight controller. I want receive the information of position and use it to update the drone state, and maybe a spawn new anchors triggered by matching some condition. Sorry for the delay, i haven't notice your reply before today

**Comment by bekirbostanci** [comment]
@lucasantoro do you want to use real world or simulation ? This is simulation repo but i designed for 2d operation but you can change little bit and use for your simulation. Also if you want I can help for real pozxy pack

**Comment by lucasantoro** [comment]
My plan is to set-up a simulation and test some script of motion. Then deploy for real world.
Now my simulation for the drone with PX4  works, i'm able to move the drone, but i don't understand how to integrate your package in my simulation. I'm using ubuntu 18.04 with ros melodic. 
I have to publish the information of position in a specific topic, after this i need to create new anchor while the simulation is running.
For the real world i have a drone with a minipixhawk and RPI 3B+

**Comment by bekirbostanci** [comment]
Firstly you have to run your gazebo simulation after than run your rviz config 
After this step is completed 
1. run rqt 
2. in rqt window "Plugins" => "Topics" => "Topic Monitor" 
3. in that window you have to find /gazebo/model_states/ topic and checked that line 
4. control your robot pose in which parameter  for example ['ground_plane','robot_symbol','turtlebot_waffle'] in thise case your index 2 
5. go repo folder /launch/uwb_manually_initializing.launch file and change modelstate_index parameter 
 ```
  <node pkg="pozyx_simulation" name="pozyx_simulation"  type="uwb_simulation.py" output="screen">
        <param name="modelstate_index" value="2" />
```
For this process get your robot or drone real position than you have to place uwb anchor in maps. 
1. go repo folder /launch/uwb_anchors_set.launch and open 
2. for each uwb anchor's set a name and position for example 
```
<launch>
   <node pkg="tf" type="static_transform_publisher" name="uwb_anchor_0x6e36" args="1.4 2.0 0.0 0 0 0 1 map uwb_anchor_0 100" />
   <node pkg="tf" type="static_transform_publisher" name="uwb_anchor_0x6e33" args="-1.4 2.0 0.0 0 0 0 1 map uwb_anchor_1 100" />
   <node pkg="tf" type="static_transform_publisher" name="uwb_anchor_0x6e49" args="1.4 -2.0 0.0 0 0 0 1 map uwb_anchor_2 100" />   
   <node pkg="tf" type="static_transform_publisher" name="uwb_anchor_0x6e30" args="-1.4 -2.0 0.0 0 0 0 1 map uwb_anchor_3 100" />
</launch>
```
3. go /src/uwb_simulation.py file and add your anchors 

```
def uwb_simulate(sensor_pos):
    while not rospy.is_shutdown():
        time.sleep(0.1)
        all_distance = [] 
        all_destination_id = []

        for i in range(len(sensor_pos)):
            #calculate distance uwb to robot for all anchors 
            dist = calculate_distance(sensor_pos[i])   
            all_distance.append(dist) 
        
        #uwb_anchors_set.launch same order (not important for simulation)
        all_destination_id.append(0x694b)
        all_destination_id.append(0x6948)
        all_destination_id.append(0x694f)
        all_destination_id.append(0x694a)
            
        #publish data with ROS             
        publish_data(all_destination_id , all_distance)  
```

Now you can run. Yes it is little bit confusing but it is working :) 
1. Firstly you can call anchors 
`roslaunch pozyx_simulation uwb_anchors_set.launch `
2. After this run main calculation script 
`roslaunch pozyx_simulation uwb_manually_initializing.launch`

If you want to check you can use 
`rostopic echo /uwb_data_topic` 

this process give robot to uwb_anchor distance for example 
```
destination_id: [26955, 26952, 26959, 26954]
distance: [4192.039813830616, 2564.0268225317145, 3703.2810901751322, 1621.13755039097]
stamp: 
  - 
    secs: 1039
    nsecs: 440000000
  - 
    secs: 1039
    nsecs: 440000000
  - 
    secs: 1039
    nsecs: 440000000
---
```

If you want to calculate your position you have to use another pack
https://github.com/bekirbostanci/ieuagv_localization
This pack use kalman filter method but fuse 2 sensors odom and uwb so that directly you can not this topic but if you can I can create a script it is not very hard. 

If you have another question feel to free :) 
Good luck

**Comment by lucasantoro** [comment]
Awesome! In these days i will try to implement it following your suggenstions. In case i will write here! Thank you very much for your time and consideration! You are super!!! 👍

**Comment by bekirbostanci** [comment]
you are welcome 
if you need to help, please write again have a nice day
