### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by lpmrz** [bekirbostanci/ros_pozyx_simulation#4]
Hello, very nice work!

My question is; is this scalable to multi robots? I am using it perfectly with a single agent, but when I spawn multiple agents, it gives errors. Error is down below. I changed the topic name accordingly but still there is a problem.
![Screenshot from 2021-08-09 11-45-55](https://user-images.githubusercontent.com/18270807/128680547-b63a3f84-967e-4799-a0c1-9b5ebde4695e.png)

**Comment by bekirbostanci** [comment]
Firstly thank you for nice comment. I didn't write this app for multi-robots but of course it can be used for multi-robots as well. 
Firstly you have to change uwb_simulation.py script for each robot
 - change your 'gazebo/model_states' topic to your multi robot name for example if you have a 3 different robot you have to copy 3 different uwb_simulation.py and than you have to change 'gazebo/model_states' to your real robot position topic 
 - change your publisher topic name 'uwb_data_topic' to 'uwb_data_topic_(robot_name)' 

after the these changes check your uwb_data_topic with rostopic echo if all the messages published you're on the right track 
Now the last step you have to change the Kalman Filter algorithm. Again you have to copy for each robot this script or you can give a argument. 
- Firstly change to subscription 'uwb_data_topic_(robot_name)' topic because normally that is a static value but now we have to do with dynamically
- Seconly you have to again change to publisher topic 'localization_data_topic' this is also static. 

If you can do all of the changes you can run with multi robot. If you have any question please you can ask.

**Comment by lpmrz** [comment]
NOTE: I solved this issue by setting the odom_hz manually. Still I would appreciate if you can tell me what is wrong.

Thank you for your reply, I did most of the changes you mentioned. I have multiple uwb_simulation files and they publish correct datas. I also created multiple kalman_filter_localization files, however I get the same error when I try to run them. Error and my changes on the kalman file are as below;

![Screenshot from 2021-08-10 16-46-05](https://user-images.githubusercontent.com/18270807/128878334-6c62e6ea-9516-4477-a1e5-c0936b459c35.png)
![Screenshot from 2021-08-10 16-46-16](https://user-images.githubusercontent.com/18270807/128878344-24a34cdc-a928-499a-8a33-86936c961081.png)

**Comment by bekirbostanci** [comment]
Actually I used this answers in the ros and it works in my tests but perhaps it would be more correct to give it as an argument at the launch file.
https://answers.ros.org/question/259709/get-hz-bw-from-rostopic-programatically/

**Comment by lpmrz** [comment]
Thank you for your replies, have a nice day.
